version: '3.9'

services:
  postgres:
    container_name: postgres
    env_file: ${ENV_FILE}
    image: postgres:14
    shm_size: 2gb
    restart: always
    volumes: 
      - postgres_vol:/var/lib/postgresql/data:cached
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - ergopad-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    env_file: ${ENV_FILE}
    image: redis
    restart: always
    volumes: 
      - redis_vol:/data # redis persistence
    ports: 
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - ergopad-net
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    entrypoint: redis-server --appendonly yes

volumes:
  postgres_vol:
  redis_vol:

networks:
  ergopad-net:
    external: true
