GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ergopad;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ergopad;
GRANT ALL PRIVILEGES  ON ALL TABLES IN SCHEMA public TO ergopad;
